baseURL = 'https://davidsalter.github.io/'
languageCode = 'en-us'
title = 'Doobries Domain'
theme = 'maverick'

[params]
  logo = '/assets/favicon.ico'
  description = "A blog about software development and other random thoughts"
  author = 'David Salter'

  [params.comments]
    enabled = true
    githubRepo = 'davidsalter/davidsalter.github.io'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 2

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
